server:
  port: 8080

flyway:
  locations: sql

spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:app.db
    tomcat:
      max-active: 1
      default-auto-commit: false

logging:
  level:
    root: INFO
